depth_void_to_float:
  invalid_depth_value: 0

ground_height_from_depth:
  ransac_iterations: 300
  inlier_threshold: 0.01

height_binary_morphology:
  floor_noise_margin: 0.04
  min_area: 100

multi_filter_contour_processor:
  dilate_count: 2
  min_frames_confirm: 5

mask_to_pointcloud:
  frame_id: camera_link